name: ci-ror-workflow-v3

on:
  workflow_call:
    inputs:
      env:
        description: 'the environment'     
        type: string
        default: 'dev'
        required: true
      skip_artefact_caching:
        description: 'set to true if there are no unit-test artefacts'
        type: boolean
        required: false
        default: false
    secrets:
      grid_git_token:
        required: false

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Unit Test
        run: |
          docker-compose -f docker-compose.ci.yml -p 123 build \
            --build-arg ENV=${{ inputs.env }} --build-arg GIT_TOKEN=${{ secrets.grid_git_token }} \
            --build-arg CI=true web
          docker-compose -f docker-compose.ci.yml -p 123 run -u $(id -u) \
            -e HOME=/tmp -e RAILS_ENV=test web \
            bundle exec rspec --format documentation --format RspecJunitFormatter --out results.xml            
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: '**/results.xml'
      - name: collect unit-test artefacts
        if: ${{ inputs.skip_artefact_caching != true }}
        run: |
          mkdir unit-test-artefacts
          cp tmp/coverage/.resultset.json unit-test-artefacts/.resultset.json
          cp tmp/coverage/coverage.json unit-test-artefacts/coverage.json
          cp results.xml unit-test-artefacts/results.xml
          ls -lah unit-test-artefacts
      - name: Cache unit-test artefacts
        if: ${{ inputs.skip_artefact_caching != true }}
        uses: actions/cache@v2
        with:
          path: unit-test-artefacts
          key: unit-test-artefacts-${{ github.run_number }}
